name = "boxed"
description = "Letterboxed solver"
version = "0.1.0-dev"

authors = ["R Srinivasan"]
maintainers = ["R Srinivasan <rajasrinivasan@hotmail.com>"]
maintainers-logins = ["rajasrinivasan"]

executables = ["boxed"]

[build-switches]
development.style_checks = "No"
