name: windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup alr
      uses: alire-project/setup-alire@v2
      
    - name: Build
      run: >
        cd boxed ;
        python3 version.py ${{github.ref_name}} ${{github.sha}} ${{github.run_number}} ${{github.workflow}} ;
        mv revisions.ads src ;
        alr build ; bin/boxed
      shell: bash
      
    - name: Publish
      uses: actions/upload-artifact@v3
      with:
          name: "artifacts"
          path: |
            boxed/bin/boxed.exe
